name: bt_tuan6
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  sqflite: ^2.3.3+1
  path_provider: ^2.1.3
  path: ^1.9.0
  uuid: ^4.4.0
  quickalert: ^1.1.0
  image_picker: ^1.1.2

flutter:
  uses-material-design: true
  assets:
    - assets/
